### ISSUE TITLE
Choose a suitable license to your package and justify your choice

### ISSUE THREAD

**Issue by Nicole-Tu97** [UBC-MDS/financial_analyzer#94]

**Comment by rafecchang** [comment]
https://choosealicense.com a source to choose license from

**Comment by alanpow** [comment]
So in lecture we talked about why licenses are so important... and to quickly mention it, it seems lie they are most important or our software for specifying how other people can make use of our package, how they can modify it, and how they are allowed to distribute it.

So to decide which license is best suitable for us, I guess we need to understand where we want out package to go from here, do we plan on work on it on the future, do we care how it is altered moving forward, and really how connected are we to it? Do we care about the recognition? Do we want to police how it is developed and what people do with it, and claim as their own?

**Comment by alanpow** [comment]
We selected the MIT License, as per what we usually do with most of our work. Looking into the MIT license it seems like it is the most simple and straight forward one. It's key benefits seem to be its simple and permissive: so it allows for "The It lets people do almost anything they want with your project, like making and distributing closed source versions". I am ok with this because I personally do not this this package we made is extremely ground breaking and doesn't need to be gate kept. I'd like it to be a stepping stone for others to do just about anything they'd like with it, though it would be nice for none closed source versions to be made of it, I wouldn't want us not allowing that to stop people from using our package for their own uses. I like that it allow for our package to be very open source and hopefully someone will make use of this package knowing how little of a hurdle the legalities will be with using it, sourcing it, and referencing it. Are you guys worried about the lack of protection, specifically for things like patenting?

**Comment by chrisgqy** [comment]
Yeah I think one of the downfalls of  MIT Licence is that our intellectual content is not protected. The MIT License does not explicitly grant patent rights. Even though it's generally interpreted to implicitly grant the rights, there's still this lack of clarity that can cause problems. Another thing is that MIT License does not require that the source code be made available when distributing the software. This can cause us to loose the "ownership" of the codes. 
That being said, I don't think here we are having a very complicated packages. Our package can be easily recreated, and I don't think I mind it if someone else use the code without citing.

**Comment by Nicole-Tu97** [comment]
While the MIT License offers simplicity and permissiveness, allowing users to freely utilize, modify, and distribute our package, there are concerns about the lack of explicit patent protection and the potential loss of ownership if the source code is not made available. However, given the nature of our package and its relatively straightforward composition, along with our openness to others using the code without citation, the MIT License aligns well with our goals of fostering accessibility and collaboration in the development and utilization of the software.

**Comment by rafecchang** [comment]
I see where you all are coming from. If we are concerned, we can use "GNU General Public License v3.0." However, for the innovativeness of our code, I don't think it will be necessary.
