### ISSUE TITLE
Address feedback to improve the package

### ISSUE THREAD

**Issue by Nicole-Tu97** [UBC-MDS/financial_analyzer#95]

**Comment by alanpow** [comment]
I had an error when I was trying to set up the package environment when running the code you included in the README. Running conda create -n --financial_analyzer python=3.9 -y gave me the error conda create: error: argument -n/--name: expected one argument. There wasn't an environment .yml file in the project, but I used my base environment and things were working.
This is a very small issue, but I don't think you should include the function parameters when listing the package's functions in the README. It makes the list very busy to look at and harder to parse through. I also think the code underneath the Usage sub-header is a little redundant, and you could include a link to the documentation or vignette here instead.
Some of the latex in your documentation is not rendering properly. Under "Return on Investment Calculation" the first sentence reads Now we will calcuate the percentage return on investment (ROI,) which is $\frac{\text{current value}-\text{initial investment}}{\text{initial investment}}\times 100$.. There are also a couple small spell check/grammar errors in the documentation. Copy and pasting the text into a word processor and editing would be beneficial.
The CHANGELOG has not been updated for each release of the package. There should be three separate releases (one for each milestone) with description of what has changed underneath.
There is an empty financial_analyzer.py file in the src folder, and an empty test_financial_analyzer.py file in the tests folder. I would suggest deleting these unnecessary files.
I think you have a small error in your README under the License: Alan PowPowichrowski

**Comment by alanpow** [comment]
Delightful reading your package and refreshing microeconomics!

Example usage: Under the roi section, some Latex is not rendering correctly.
Example usage: Currently, the four functions share three similar example backgrounds and each has a complete introduction. It might be helpful to reduce some of the redundant information to make the example usage more concise.
pyproject.toml: Package version in the pyproject toml file has not been updated and is still 0.1.0

**Comment by alanpow** [comment]
The document is overall good, well-written, and seems useful.

Including the command 'pip install financial_analyser' before the setup instructions is confusing, as this step should be the final one in the setup process, but it appears at the beginning.
Both the 'src/financial_analyser' and 'dist/financial_analyser' directories contain the 'init.py' and 'function.py' scripts. Having only one copy of these functions would be preferable to avoid repetition.
While it's a minor issue, 'examples.ipynb' could be improved by featuring multiple examples and graphs, rather than just one.
In the unit tests for 'units_for_target_profit', it would have been beneficial to include more extreme cases, such as scenarios with negative profit or non-numeric input values.

**Comment by alanpow** [comment]
The package is generally good, but it could be more comprehensive and inclusive.
While the package excels in providing comprehensive documentation, including installation instructions and function documentation, it falls short in offering practical examples for all user-facing functions. The inclusion of vignettes and more extensive examples would significantly improve the user experience, aiding in understanding and application of the package's functionality.
